# Generated by Django 4.2.7 on 2023-11-30 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valItems', models.CharField(max_length=255)),
                ('priceItems', models.IntegerField(default=0)),
                ('IDitems', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='participants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fName', models.CharField(max_length=255)),
                ('lName', models.CharField(max_length=255)),
                ('emailAdd', models.CharField(max_length=255)),
                ('IDparticipants', models.CharField(max_length=1000)),
                ('itemID', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fName', models.CharField(max_length=255)),
                ('lName', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('IDparticipants', models.CharField(max_length=1000)),
                ('item', models.CharField(max_length=1000)),
                ('total_value', models.FloatField(default=0)),
                ('fair_share', models.FloatField(default=0)),
                ('pay', models.FloatField(default=0)),
                ('get', models.FloatField(default=0)),
                ('link', models.CharField(max_length=1000)),
            ],
        ),
    ]
