# Generated by Django 4.2.7 on 2023-12-03 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_items_item_rename_participants_participant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bidding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDParticipant', models.CharField(max_length=1000)),
                ('total', models.FloatField()),
                ('item1', models.IntegerField(default=0)),
                ('item2', models.IntegerField(default=0)),
                ('item3', models.IntegerField(default=0)),
                ('item4', models.IntegerField(default=0)),
                ('item5', models.IntegerField(default=0)),
                ('item6', models.IntegerField(default=0)),
                ('item7', models.IntegerField(default=0)),
                ('item8', models.IntegerField(default=0)),
                ('item9', models.IntegerField(default=0)),
                ('item10', models.IntegerField(default=0)),
            ],
        ),
    ]
