# Generated by Django 4.2.2 on 2023-12-04 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_bidding'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='participants',
            field=models.ManyToManyField(related_name='items', to='base.participant'),
        ),
    ]
