# Generated by Django 4.2.2 on 2023-12-04 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_item_participants'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='valItems',
            new_name='property_name',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='emailAdd',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='fName',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='lName',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='item',
            name='IDitems',
        ),
        migrations.RemoveField(
            model_name='item',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='item',
            name='priceItems',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='IDparticipants',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='itemID',
        ),
        migrations.AddField(
            model_name='item',
            name='min_bid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
    ]
