# Generated by Django 4.2.7 on 2023-12-05 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_valitems_item_property_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='Items_ID',
            field=models.CharField(default='none', max_length=1000),
        ),
        migrations.AddField(
            model_name='participant',
            name='IDItems',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='IDParticipants',
            field=models.CharField(default='none', max_length=1000),
        ),
        migrations.AlterField(
            model_name='participant',
            name='email',
            field=models.CharField(max_length=255),
        ),
    ]
